# -*- coding: utf-8 -*-
__author__ = 'Antonio Masotti'

'''
DOC: Dieses Modul definiert und initialisiert die Tabelle der Autoren in der SQLite-Datenbank.

'''

# IMPORTE
from common.grund_einstellungen import db # die Datenbank
from models.db_klassen import Autoren # die Python-Klasse (=SQL-abelle) der Autoren, deren Instanzen hier im Folgenden definiert werden

# Initialisierung der einzelnen Autoren
Aeschines = Autoren(name="Aeschines", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Aeschines&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Aeschylus = Autoren(name="Aeschylus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Aeschylus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Andocides = Autoren(name="Andocides", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Andocides&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Anna_Komnene = Autoren(name="Anna Komnene", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Anna Komnene&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Antiphon = Autoren(name="Antiphon", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Antiphon&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Apollodorus = Autoren(name="Apollodorus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Apollodorus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Apollonius_Rhodius = Autoren(name="Apollonius Rhodius", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Apollonius Rhodius&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Appian = Autoren(name="Appian", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Appian&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Aretaeus = Autoren(name="Aretaeus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Aretaeus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Aristophanes = Autoren(name="Aristophanes", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Aristophanes&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Aristotle = Autoren(name="Aristotle", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Aristotle&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Bacchylides = Autoren(name="Bacchylides", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Bacchylides&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Callimachus = Autoren(name="Callimachus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Callimachus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Demades = Autoren(name="Demades", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Demades&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Demosthenes = Autoren(name="Demosthenes", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Demosthenes&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Dinarchus = Autoren(name="Dinarchus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Dinarchus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Diodorus_Siculus = Autoren(name="Diodorus Siculus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Diodorus Siculus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Diogenes_Laertius = Autoren(name="Diogenes Laertius", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Diogenes Laertius&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Epictetus = Autoren(name="Epictetus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Epictetus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Euclid = Autoren(name="Euclid", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Euclid&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Euripides = Autoren(name="Euripides", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Euripides&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Flavius_Josephus = Autoren(name="Flavius Josephus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Flavius Josephus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Galen = Autoren(name="Galen", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Galen&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Gorgias = Autoren(name="Gorgias", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Gorgias&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Herodotus = Autoren(name="Herodotus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Herodotus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Hesiod = Autoren(name="Hesiod", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Hesiod&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Hippocrates = Autoren(name="Hippocrates", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Hippocrates&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Homer = Autoren(name="Homer", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Homer&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Hyperides = Autoren(name="Hyperides", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Hyperides&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Isaeus = Autoren(name="Isaeus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Isaeus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Isocrates = Autoren(name="Isocrates", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Isocrates&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Lycurgus = Autoren(name="Lycurgus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Lycurgus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Lysias = Autoren(name="Lysias", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Lysias&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
NA = Autoren(name="NA", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=NA&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Old_Oligarch = Autoren(name="Old Oligarch", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Old Oligarch&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Pausanias = Autoren(name="Pausanias", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Pausanias&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Pindar = Autoren(name="Pindar", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Pindar&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Plato = Autoren(name="Plato", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Plato&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Plutarch = Autoren(name="Plutarch", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Plutarch&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Polybius = Autoren(name="Polybius", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Polybius&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Sophocles = Autoren(name="Sophocles", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Sophocles&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Strabo = Autoren(name="Strabo", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Strabo&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Theocritus = Autoren(name="Theocritus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Theocritus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Theophrastus = Autoren(name="Theophrastus", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Theophrastus&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Thucydides = Autoren(name="Thucydides", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Thucydides&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")
Xenophon = Autoren(name="Xenophon", link="http://artflsrv02.uchicago.edu/cgi-bin/perseus/search3torth?dbname=GreekApr19&word=&OUTPUT=conc&ORTHMODE=ORG&CONJUNCT=PHRASE&DISTANCE=3&author=Xenophon&title=&POLESPAN=5&THMPRTLIMIT=1&KWSS=1&KWSSPRLIM=500&trsortorder=author%2C+title&editor=&pubdate=&language=&shrtcite=&genre=&sortorder=author%2C+title&dgdivhead=&dgdivtype=&dgsubdivwho=&dgsubdivn=&dgsubdivtag=&dgsubdivtype=")


# Alle Autoren werden in einer Liste gespeichert
AUTORI = [Aeschines, Aeschylus, Andocides, Anna_Komnene, Antiphon,
          Apollodorus, Apollonius_Rhodius, Appian, Aretaeus, Aristophanes,
          Aristotle, Bacchylides,Callimachus, Demades, Demosthenes,
          Dinarchus, Diodorus_Siculus, Diogenes_Laertius,
          Epictetus, Euclid, Euripides, Flavius_Josephus, Galen, Gorgias,
          Herodotus, Hesiod,
          Hippocrates, Homer, Hyperides, Isaeus, Isocrates,
          Lycurgus, Lysias, NA, Old_Oligarch,
          Pausanias, Pindar, Plato, Plutarch, Polybius, Sophocles, Strabo,
          Theocritus, Theophrastus, Thucydides, Xenophon]

# Aus der Liste wird die Tabelle der Autoren generiert
def add_neue_autoren():
    for autor in AUTORI:
        instanz = Autoren.query.filter_by(name=autor.name).first()
        if instanz:
            print(f"{autor.name} schon vorhanden; wird übersprungen")
        else:
            print(f"{autor.name} wird gespeichert.")
            db.session.add(autor)
            db.session.commit()
